# -*- coding: utf-8 -*-
"""Josephine Fordward Chaining UTS Kelompok 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b23jNGkesPg4WN_xsRh73iVyxMUzDQHA
"""

import pandas as pd

# upload file
from google.colab import files
uploaded = files.upload()

# load dataset
df = pd.read_csv('water_potability_fix.csv')

# cek data
df.head()

def forward_chaining(data):
    if 6.0 < data['ph'] < 9.0:
        if data['Hardness'] < 300:
            return "Layak Minum"
    return "Tidak Layak"

for i in range(10):
    data = df.iloc[i]

    # Rule-based
    fc = forward_chaining(data)

    print(f"\nData ke-{i+1}")
    print(f"Forward Chaining : {fc}")