# -*- coding: utf-8 -*-
"""Khuzaima Filla Januartha_Naive Bayes_UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwwyjRvdz9I0yOn8gQ4UsFKlIrzBkO9f

**IMPORT LIBRARY**
"""

import pandas as pd

# upload file
from google.colab import files
uploaded = files.upload()

# load dataset
df = pd.read_csv('water_potability_fix.csv')

# cek data
df.head()

"""**NAIVE/TEOREMA BAYES**"""

#Teorema Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

X = df.drop('Potability', axis=1)
y = df['Potability']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = GaussianNB()
model.fit(X_train, y_train)

pred = model.predict(X_test)

"""Output:"""

print("===== HASIL PREDIKSI NAIVE BAYES (10 DATA) =====")

for i in range(10):
    # Logika konversi angka ke label teks
    nb = "Layak Minum" if pred[i] == 1 else "Tidak Layak"
    aktual = "Layak Minum" if y_test.values[i] == 1 else "Tidak Layak"

    # Cetak output
    print(f"Data ke-{i+1}")
    print(f"Naive Bayes : {nb}")
    print(f"Aktual      : {aktual}")

    # Indikator Kecocokan (Opsional, biar enak liatnya)
    status = "✅ SESUAI" if nb == aktual else "❌ SALAH"
    print(f"Status      : {status}")
    print("-" * 35)