# -*- coding: utf-8 -*-
"""MochamadZacky_UTS_SBP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXUVyHx2efLxVsGjwMPlX35q9aEoA66a
"""

import pandas as pd

df = pd.read_csv('water_potability_fix.csv')

df.info()
df.describe()

#Certainty Factor (CF)
def certainty_factor(ph, hardness):
    cf_ph = 0.8 if 6.0 < ph < 9.0 else 0.4
    cf_hardness = 0.7 if hardness < 300 else 0.5

    cf_combine = (cf_ph + cf_hardness) / 2
    return cf_combine

for i in range(10):
    data = df.iloc[i]

    # Hitung CF
    cf_val = certainty_factor(data['ph'], data['Hardness'])

    # Tentukan hasil
    if cf_val > 0.6:
        hasil = "Layak Minum"
    else:
        hasil = "Tidak Layak"

    print(f"\nData ke-{i+1}")
    print(f"Certainty Factor: {hasil} (CF = {cf_val:.2f})")

!git clone https://github.com/khuzaimafilla/pblsemester6.git

# Commented out IPython magic to ensure Python compatibility.
# %cd pblsemester6

!git pull origin main

!git add .

!git config --global user.email "muhammadzaky86930@gmail.com"
!git config --global user.name "mochamadzacky"

