# -*- coding: utf-8 -*-
"""PuteraBhagaswara_UTSSBB_Backchaining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4OJVwMjrM48VVk67heU1kL5CUJihOZb
"""

import pandas as pd

# upload file
from google.colab import files
uploaded = files.upload()

# load dataset
df = pd.read_csv('water_potability.csv')

# cek data
df.head()

#backward_chaining
def backward_chaining(data):
    goal = "Layak Minum"

    if not (6.0 < data['ph'] < 9.0):
        return "Tidak Layak"
    if data['Hardness'] >= 300:
        return "Tidak Layak"

    return goal

for i in range(10):
    data = df.iloc[i]

    # Rule-based
    bc = backward_chaining(data)

    print(f"\nData ke-{i+1}")
    print(f"Backward Chaining: {bc}")